const contacts = require('./contacts/contacts.service.js');
const coupons = require('./coupons/coupons.service.js');
const users = require('./users/users.service.js');
const roles = require('./roles/roles.service.js');
const colors = require('./colors/colors.service.js');
const countries = require('./countries/countries.service.js');
const stateProvinces = require('./state_provinces/state_provinces.service.js');
const phones = require('./phones/phones.service.js');
const emails = require('./emails/emails.service.js');
const addresses = require('./addresses/addresses.service.js');
const persons = require('./persons/persons.service.js');
const points = require('./points/points.service.js');
const comments = require('./comments/comments.service.js');
const reviews = require('./reviews/reviews.service.js');
const customers = require('./customers/customers.service.js');
const companies = require('./companies/companies.service.js');
const companyTypes = require('./company-types/company-types.service.js');
const services = require('./services/services.service.js');
const products = require('./products/products.service.js');
const qrcodes = require('./qrcodes/qrcodes.service.js');
const banners = require('./banners/banners.service.js');
const images = require('./images/images.service.js');
const couponTypes = require('./coupon-types/coupon-types.service.js');
const stores = require('./stores/stores.service.js');
const departments = require('./departments/departments.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(contacts);
  app.configure(coupons);
  app.configure(users);
  app.configure(roles);
  app.configure(colors);
  app.configure(countries);
  app.configure(stateProvinces);
  app.configure(phones);
  app.configure(emails);
  app.configure(addresses);
  app.configure(persons);
  app.configure(points);
  app.configure(comments);
  app.configure(reviews);
  app.configure(customers);
  app.configure(companies);
  app.configure(companyTypes);
  app.configure(services);
  app.configure(products);
  app.configure(qrcodes);
  app.configure(banners);
  app.configure(images);
  app.configure(couponTypes);
  app.configure(stores);
  app.configure(departments);
};
